// Mocks generated by Mockito 5.4.5 from annotations
// in todo_app/test/data/repositories/todo_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/data/datasources/todo_local_datasource.dart' as _i5;
import 'package:todo_app/data/datasources/todo_remote_datasource.dart' as _i3;
import 'package:todo_app/domain/entities/todo_entity.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodoEntity_0 extends _i1.SmartFake implements _i2.TodoEntity {
  _FakeTodoEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRemoteDataSource extends _i1.Mock
    implements _i3.TodoRemoteDataSource {
  MockTodoRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TodoEntity>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue: _i4.Future<List<_i2.TodoEntity>>.value(
              <_i2.TodoEntity>[],
            ),
          )
          as _i4.Future<List<_i2.TodoEntity>>);

  @override
  _i4.Future<_i2.TodoEntity> getTodoById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoById, [id]),
            returnValue: _i4.Future<_i2.TodoEntity>.value(
              _FakeTodoEntity_0(this, Invocation.method(#getTodoById, [id])),
            ),
          )
          as _i4.Future<_i2.TodoEntity>);

  @override
  _i4.Future<_i2.TodoEntity> createTodo(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#createTodo, [title]),
            returnValue: _i4.Future<_i2.TodoEntity>.value(
              _FakeTodoEntity_0(this, Invocation.method(#createTodo, [title])),
            ),
          )
          as _i4.Future<_i2.TodoEntity>);
}

/// A class which mocks [TodoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoLocalDataSource extends _i1.Mock
    implements _i5.TodoLocalDataSource {
  MockTodoLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TodoEntity>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue: _i4.Future<List<_i2.TodoEntity>>.value(
              <_i2.TodoEntity>[],
            ),
          )
          as _i4.Future<List<_i2.TodoEntity>>);

  @override
  _i4.Future<void> cacheTodos(List<_i2.TodoEntity>? todos) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTodos, [todos]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.TodoEntity> createTodo(_i2.TodoEntity? todo) =>
      (super.noSuchMethod(
            Invocation.method(#createTodo, [todo]),
            returnValue: _i4.Future<_i2.TodoEntity>.value(
              _FakeTodoEntity_0(this, Invocation.method(#createTodo, [todo])),
            ),
          )
          as _i4.Future<_i2.TodoEntity>);

  @override
  _i4.Future<_i2.TodoEntity> updateTodo(_i2.TodoEntity? todo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [todo]),
            returnValue: _i4.Future<_i2.TodoEntity>.value(
              _FakeTodoEntity_0(this, Invocation.method(#updateTodo, [todo])),
            ),
          )
          as _i4.Future<_i2.TodoEntity>);

  @override
  _i4.Future<void> deleteTodo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.TodoEntity?> getTodoById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoById, [id]),
            returnValue: _i4.Future<_i2.TodoEntity?>.value(),
          )
          as _i4.Future<_i2.TodoEntity?>);
}
